Build update modules
genomic-medicine-sweden/poppy pull request #51
Opened 2024-02-05 13:24 UTC by elleira

2024-03-07 15:04 UTC, elleira commented
Here comes my complete mess of PR :sweat_smile:  

- I have updated a lot of modules and requirements. 
- Added some more steps for pindel vcfs such as adding an AF field, normalizing the variants and annotating the vcf with vep (if the file does not contain any variants vep fails therefor that is checked before). 
- I have also added tool-version logging based on the new hydra [help-code](https://hydra-genetics.readthedocs.io/en/latest/development/help_code/#version-logging). This can then be included in the MultiQC-report under Software Versions table.
- I have also run Poppy through with an actual dataset and added/adapted filtering steps to limit the results some.
- I also added some rough drafts of the documentation based on [Twist Solids layout](https://twist-solid.readthedocs.io/en/latest/) just to get it started

2024-03-08 07:11 UTC, maehler requested changes
Well done! There are a couple of things that need addressing, but overall I think it looks good.

2024-03-08 07:11 UTC, maehler commented on workflow/rules/annotation_vep_pindel.smk
I might be missing something, but wouldn't it be simpler if the rules that consume this file uses an input function that returns either the annotated file or the original, empty file? This works, but I can't help feeling it could be made in a simpler way.

2024-03-08 07:11 UTC, maehler commented on config/config_hard_filter_germline.yaml
I don't like that this more or less puts a dependency on the VEP version that is used, but I also don't really see a way around it right now. Just something to keep in mind.

2024-03-08 08:45 UTC, elleira commented on workflow/scripts/annotation_vep_pindel.sh
> +#!/usr/bin/sh
Changed!

2024-03-08 08:45 UTC, elleira commented on config/config_soft_filter_somatic.yaml
> +    soft_filter: "False"
Very true, I changed it back!

2024-03-08 08:46 UTC, elleira commented on workflow/schemas/rules.schema.yaml
> +            description: annotated (or incase of empty just copied) vcf file
Went through all yaml files and formatted them so it should be better now :sweat_smile:

2024-03-08 08:49 UTC, elleira commented on workflow/rules/annotation_vep_pindel.smk
I was thinking that too, the i got stuck on that maybe we need a track record that pindel were used even if there are no results. At the same time it is quite unnecessary since I'm guessing most ppl will look into the pipeline documentation not go through massive vcf-headers..

2024-03-08 08:50 UTC, elleira commented on config/config_hard_filter_germline.yaml
Yes and keeping the old annotation put a dependency to use an old version of vep :upside_down_face:

2024-03-08 09:18 UTC, maehler commented on workflow/rules/annotation_vep_pindel.smk
Let's keep it like this for now, but keep it in mind for future refactoring.

2024-03-08 09:21 UTC, maehler approved these changes
I don't have anything obvious to comment on. Great work!

2024-03-08 09:21 UTC, maehler commented
I would suggest that you do a rebase and merge, to keep all the history since it's so diverse, rather than squashing.

2024-03-08 09:34 UTC, merged